:Author: Derek Thompson (TeamLoki)
:Email: teamloki18@gmail.com
:Date: 25/11/2018
:Revision: version#1
:License: Public Domain

= Project: Robotic Arm controller from PC

==Description:

  Control a 3-axis robotic arm by entering commands via the serial terminal.
  This program is designed for an instruction set as follows:
  Servo number (0-2) indicating the servo motor that you want to command delimited by a ":" 
  followed by a one-to-three digit number (0-180) indicating the angle that the servo should 
  move to.  Each instruction set is delimited by a ","
  
  =Example Instructions: 
  2:120 - Servo 2, move to 120 degree position.
  0:0 - Servo 0, move to 0 degree position.
  
  The program can accomadate multiple instruction sets sent at one time, allowing the user to 
  write and send "programs" for the robot arm to follow.
  
  =Example Program:
  2:80,0:0,1:0,2:145,1:30,0:150,2:90,1:90,

== Step 1: Installation

1. Upload this sketch to Arduino platform (Uno or Mega).
2. Open serial monitor, set newline, 9600 baud
3. Use external 5V power source to drive servos!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 robot_arm_alpha                => Arduino sketch folder
  ├── robot_arm_alpha.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under the public domain.

=== Contributing
To contribute to this project please contact TeamLoki https://id.arduino.cc/TeamLoki

=== BOM
Add the bill of the materials you need for this project.

|===
| ID  | Part name           | Part number | Quantity
| N/A | 3-axis Robotic arm  |  101-20-128 | 1
| N/A | Red LED             | 2345-asdf   | 5
| N/A | Arduino Uno         | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
